=== aksonenko/ServletMysqlCrudSample/ServletMysqlCrudSample/booksDtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT books (book*)>
<!ELEMENT book (id+,name+,author+,date+)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== aksonenko/ServletMysqlCrudSample/ServletMysqlCrudSample/books.xml
<?xml version="1.0"?>
<!DOCTYPE university SYSTEM "booksDTD.dtd">
<books>
	<book>
		<id>1</id>
		<name>Java</name>
		<author>Shiltd</author>
		<date>12/10/2010</date>
	</book>
	<book>
		<id>2</id>
		<name>Clean code</name>
		<author>Martin</author>
		<date>12/06/2009</date>
	</book>
</books>
